CREATE TABLE market (
	id INTEGER PRIMARY KEY,
	seller TEXT,
	item_name TEXT,
	item_description TEXT,
	item_location TEXT,
	item_pic, TEXT,
	current_bid FLOAT,
	buy_out FLOAT
);

INSERT INTO market (id, seller, item_name, item_description, item_location, item_pic, current_bid, buy_out) VALUES ( 1, "Tony", "Adidas Yeezy Boost 350 V2 Black Red", "Known for their iconic collabs, once again Kanye West and adidas had brewed up more sneaker collection heat with the adidas Yeezy Boost 350 Black Red. Showing Pirate Black flashes, these come with a core black upper and sole that has a core red SPLY-350 branding on both sides. These released in November 2016 and retailed at $220.", "Castle Hill", "https://stockx-360.imgix.net/Adidas-Yeezy-Boost-350-V2-Core-Black-Red-2017/Images/Adidas-Yeezy-Boost-350-V2-Core-Black-Red-2017/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1538080256&w=1000", 50, 800 );
INSERT INTO market (id, seller, item_name, item_description, item_location, item_pic, current_bid, buy_out) VALUES ( 2, "Tony", "Adidas Yeezy Boost 350 V2 Black Red", "Known for their iconic collabs, once again Kanye West and adidas had brewed up more sneaker collection heat with the adidas Yeezy Boost 350 Black Red. Showing Pirate Black flashes, these come with a core black upper and sole that has a core red SPLY-350 branding on both sides. These released in November 2016 and retailed at $220.", "Castle Hill", "https://stockx-360.imgix.net/Adidas-Yeezy-Boost-350-V2-Core-Black-Red-2017/Images/Adidas-Yeezy-Boost-350-V2-Core-Black-Red-2017/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1538080256&w=1000", 50, 800 );
INSERT INTO market (id, seller, item_name, item_description, item_location, item_pic, current_bid, buy_out) VALUES ( 3, "Tony", "Adidas Yeezy Boost 350 V2 Black Red", "Known for their iconic collabs, once again Kanye West and adidas had brewed up more sneaker collection heat with the adidas Yeezy Boost 350 Black Red. Showing Pirate Black flashes, these come with a core black upper and sole that has a core red SPLY-350 branding on both sides. These released in November 2016 and retailed at $220.", "Castle Hill", "https://stockx-360.imgix.net/Adidas-Yeezy-Boost-350-V2-Core-Black-Red-2017/Images/Adidas-Yeezy-Boost-350-V2-Core-Black-Red-2017/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1538080256&w=1000", 50, 800 );
INSERT INTO market (id, seller, item_name, item_description, item_location, item_pic, current_bid, buy_out) VALUES ( 4, "Tony", "Adidas Yeezy Boost 350 V2 Black Red", "Known for their iconic collabs, once again Kanye West and adidas had brewed up more sneaker collection heat with the adidas Yeezy Boost 350 Black Red. Showing Pirate Black flashes, these come with a core black upper and sole that has a core red SPLY-350 branding on both sides. These released in November 2016 and retailed at $220.", "Castle Hill", "https://stockx-360.imgix.net/Adidas-Yeezy-Boost-350-V2-Core-Black-Red-2017/Images/Adidas-Yeezy-Boost-350-V2-Core-Black-Red-2017/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1538080256&w=1000", 50, 800 );
INSERT INTO market (id, seller, item_name, item_description, item_location, item_pic, current_bid, buy_out) VALUES ( 5, "Tony", "Adidas Yeezy Boost 350 V2 Black Red", "Known for their iconic collabs, once again Kanye West and adidas had brewed up more sneaker collection heat with the adidas Yeezy Boost 350 Black Red. Showing Pirate Black flashes, these come with a core black upper and sole that has a core red SPLY-350 branding on both sides. These released in November 2016 and retailed at $220.", "Castle Hill", "https://stockx-360.imgix.net/Adidas-Yeezy-Boost-350-V2-Core-Black-Red-2017/Images/Adidas-Yeezy-Boost-350-V2-Core-Black-Red-2017/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1538080256&w=1000", 50, 800 );
INSERT INTO market (id, seller, item_name, item_description, item_location, item_pic, current_bid, buy_out) VALUES ( 6, "Tony", "Adidas Yeezy Boost 350 V2 Black Red", "Known for their iconic collabs, once again Kanye West and adidas had brewed up more sneaker collection heat with the adidas Yeezy Boost 350 Black Red. Showing Pirate Black flashes, these come with a core black upper and sole that has a core red SPLY-350 branding on both sides. These released in November 2016 and retailed at $220.", "Castle Hill", "https://stockx-360.imgix.net/Adidas-Yeezy-Boost-350-V2-Core-Black-Red-2017/Images/Adidas-Yeezy-Boost-350-V2-Core-Black-Red-2017/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1538080256&w=1000", 50, 800 );
INSERT INTO market (id, seller, item_name, item_description, item_location, item_pic, current_bid, buy_out) VALUES ( 7, "Tony", "Adidas Yeezy Boost 350 V2 Black Red", "Known for their iconic collabs, once again Kanye West and adidas had brewed up more sneaker collection heat with the adidas Yeezy Boost 350 Black Red. Showing Pirate Black flashes, these come with a core black upper and sole that has a core red SPLY-350 branding on both sides. These released in November 2016 and retailed at $220.", "Castle Hill", "https://stockx-360.imgix.net/Adidas-Yeezy-Boost-350-V2-Core-Black-Red-2017/Images/Adidas-Yeezy-Boost-350-V2-Core-Black-Red-2017/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1538080256&w=1000", 50, 800 );
INSERT INTO market (id, seller, item_name, item_description, item_location, item_pic, current_bid, buy_out) VALUES ( 8, "Tony", "Adidas Yeezy Boost 350 V2 Black Red", "Known for their iconic collabs, once again Kanye West and adidas had brewed up more sneaker collection heat with the adidas Yeezy Boost 350 Black Red. Showing Pirate Black flashes, these come with a core black upper and sole that has a core red SPLY-350 branding on both sides. These released in November 2016 and retailed at $220.", "Castle Hill", "https://stockx-360.imgix.net/Adidas-Yeezy-Boost-350-V2-Core-Black-Red-2017/Images/Adidas-Yeezy-Boost-350-V2-Core-Black-Red-2017/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1538080256&w=1000", 50, 800 );
INSERT INTO market (id, seller, item_name, item_description, item_location, item_pic, current_bid, buy_out) VALUES ( 9, "Tony", "Adidas Yeezy Boost 350 V2 Black Red", "Known for their iconic collabs, once again Kanye West and adidas had brewed up more sneaker collection heat with the adidas Yeezy Boost 350 Black Red. Showing Pirate Black flashes, these come with a core black upper and sole that has a core red SPLY-350 branding on both sides. These released in November 2016 and retailed at $220.", "Castle Hill", "https://stockx-360.imgix.net/Adidas-Yeezy-Boost-350-V2-Core-Black-Red-2017/Images/Adidas-Yeezy-Boost-350-V2-Core-Black-Red-2017/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1538080256&w=1000", 50, 800 )